### ISSUE TITLE
Sub category is not visible

### ISSUE THREAD

**Issue by vnnogileuser** [pratikmage/magento2_subcategory#2]
Sub category is not visible on category page

**Comment by pratikmage** [comment]
You have create static block and assign static block for category ?
Note:make sure is anchor is yes

**Comment by vnnogileuser** [comment]
Yes Pratik it's work for me. but issue is its showing the all subcategories in factes area and all product are gone. i wanted to show like this
URL - http://www.tolexo.com/safety/gloves-and-hand-protection.html
It's showing 'safety gloves sub categories' along with its products.

**Comment by pratikmage** [comment]
it's need customization whenever i free i update code.

**Comment by vnnogileuser** [comment]
Than you very much.
You made my day.
How to accept the answer on 'http://magento.stackexchange.com' please vote that question
Yes Came to know how to show category as well as product. but ui alignment is not so good.
