### ISSUE TITLE
Admin - Issue Thumbnail images is not loading

### ISSUE THREAD

**Issue by mohsinahmed22** [pratikmage/magento2_subcategory#3]
I installed ver. 2.1.3  at admin section thumbnail is not loading after i selected to upload. My upload files has been uploaded at /catalog/tmp/catagory  but at admin and frontend its not displaying.

**Comment by pratikmage** [comment]
this is magento issue and here is link [https://github.com/magento/magento2/issues/5438](url) 
if you looking solution here is it.  [https://github.com/magento/magento2/pull/5978/files](solution)

**Comment by mohsinahmed22** [comment]
Thank you Very Much....!!!!
